
#postgresql configuration

spring.datasource.url=jdbc+:postgresql://dpg-d75kva8ule4c73csrea0-a.oregon-postgres.render.com/monwymanager
spring.datasource.username=${PQ_USERNAME}
spring.datasource.password=${PO_PASSWORD}