
#postgresql configuration

spring.datasource.url=jdbc:postgresql://dpg-d75kva8ule4c73csrea0-a.oregon-postgres.render.com/monwymanager
spring.datasource.username=monwymanager_user
spring.datasource.password=EhZqWdtFFInbbKRlLkAORILP42rnPd6s